.TH vs\-thumb 1 "05 August 2015" "Ubuntu" "Linux User's Manual"

.SH NAME
vs\-thumb \- Program to extract images from local streaming media files.

.SH SYNOPSIS
.B vs\-thumb input\-file output\-file

.SH DESCRIPTION
The \fBvs\-thumb\fP program is used by \fBthumbnailer\-service\fP(1) to extract
images from local streaming media (audio and video) files.

.SH EXIT STATUS
.TP
.B 1
Incorrect number of command\-line arguments or, if correct, no embedded artwork
was found in a media file.
.TP
.B 2
The gstreamer pipeline encountered an error during image extraction, or an embedded
image did not decode correctly.

.SH "SEE ALSO"
.B thumbnailer\-service\fR(1)\fP
